### ISSUE TITLE
Status Module Support

### ISSUE THREAD

**Issue by josephcrawfordSRH** [catppuccin/tmux#142]
Does Catppuccin only support a small subset of modules?  I have tried several time to get this to work with the format of `#{continuum_status}` and `continuum_status` but I cannot get it to load into my status bar.

```
set -g @catppuccin_status_modules_right "session cpu date_time #{continuum_status}"
```

**Comment by vdbe** [comment]
`catppuccin_status_modules_right` is a list of modules. You can add a custom module for continuum_status, is explained [here](https://github.com/catppuccin/tmux/tree/main/custom).

**Comment by josephcrawfordSRH** [comment]
@vdbe maybe i am missing something?  I am testing out with `tmux-cpu` and was unable to get it to work

`~/.config/tmux/plugins/tmux/custom/show_cpu_percentage.sh`
```
show_cpu_percentage() { # save this module in a file with the name <module_name>.sh
  local index=$1        # this variable is used by the module loader in order to know the position of this module
  local icon="$(get_tmux_option "@catppuccin_cpu_percentage_icon" "󰻠")"
  local color="$(get_tmux_option "@catppuccin_cpu_percentage_color" "#f5a97f")"
  local text="$(get_tmux_option "@catppuccin_cpu_percentage_text" "CPU")"

  local module=$(build_status_module "$index" "$icon" "$color" "$text")

  echo "$module"
}
```
I then added `#{cpu_percentage}` to my catppuccin config in tmux.conf?

**Comment by vdbe** [comment]
`#{cpu_percentage}` needs to be the `catppuccin_cpu_percentage_text` default and `cpu_percentage` will be the module name for that snippet.

However CPU is an existing module: https://github.com/catppuccin/tmux/?tab=readme-ov-file#CPU-module,
it is implemented here: https://github.com/catppuccin/tmux/blob/main/status/cpu.sh

**Comment by josephcrawfordSRH** [comment]
Thanks I will test it out with a different module my bad.

**Comment by vdbe** [comment]
You can keep testing with your cpu_percentage module and compare with with `status/cpu.sh`, just make sure the module names are different like you did above.

Good luck

**Comment by josephcrawfordSRH** [comment]
Excellent, thank you for the clarification and example for the CPU as it showed exactly what I needed to do.

**Comment by marcusorjames** [comment]
Hi Sorry to re-open this issue. But @josephcrawfordSRH is the reason you were trying to get this working because continuum stopped auto saving? According to their documentation it relies on the status to hook into.

Since using catppuccin, my saving has stopped working. 

If you managed to get it working can you share how?

I followed above and created a custom status module:

```
# Requires https://github.com/tmux-plugins/tmux-continuum

show_continuum_status() { # This function name must match the module name!
  local index icon color text module

  index=$1 # This variable is used internally by the module loader in order to know the position of this module

  icon="$(  get_tmux_option "@catppuccin_continuum_status_icon"  "" )"
  color="$( get_tmux_option "@catppuccin_continuum_status_color" "$thm_orange" )"
  text="$(  get_tmux_option "@catppuccin_continuum_status_text"  "#{continuum_status}" )"

  module=$( build_status_module "$index" "$icon" "$color" "$text" )

  echo "$module"
}
```

With my bar config as follows: ` set -g @catppuccin_status_modules_right "directory session continuum_status"`.

However it doesn't seem to work. The icon shows, with nothing to the right of it. If I reload my tmux config, it briefly flashes whatever I set as `continuum-save-interval` then disappears. At this point it updates the resurrect file, but then doesn't save on the interval.

Any help would be much appreciated.

**Comment by josephcrawfordSRH** [comment]
@marcusorjames no I did not have that issue and I stopped using continuum status sorry.

**Comment by marcusorjames** [comment]
No problem, thank you for responding.
