### ISSUE TITLE
override pane active border color

### ISSUE THREAD

**Issue by opakholis** [catppuccin/tmux#20]
Hey, I want to change the color of the panes by adding `set -g pane-active-border-style "fg=#313244"` in my own `~/.tmux.conf but it doesn't seem to work.

Is there a way to override the default style? I want similar color on active panel as in neovim screenshot

**tmux**
![image](https://user-images.githubusercontent.com/49778014/199139929-afb3ceb7-c150-4ed7-b79b-cfebdcfcc716.png)

**nvim**
![image](https://user-images.githubusercontent.com/49778014/199139889-d3c6a00c-138e-41fc-ad3a-a26d0e303572.png)

**Comment by rogeruiz** [comment]
Hey @opakholis there's no way to currently override this style using the `-g` as that is what is being set in the theme today.. Since you're looking to go against the style guide by providing your own colors, which is okay since it's local, you will need to add the `-s` to your command. It's written in the Tmux manual in an indirect way.

> Set a pane option with `-p`, a window option with `-w`, a server option with `-s`, otherwise a session option.

[=> Source for the -s command in the Tmux manual](https://www.man7.org/linux/man-pages/man1/tmux.1.html)

Search for _a server option with -s_ on the page linked above.

<img width="787" alt="Captura de pantalla 2022-11-24 a la(s) 12 38 22 a m" src="https://user-images.githubusercontent.com/706004/203702948-618c45b1-efc2-4537-b924-463cc4ac9575.png">

I have used the `#8b0000` hex color to add a dark red color to my `pane-active-border-style`. Note that the currently supported themes as part of this writing are using the `$thm_blue` which is set to a different blue for each theme flavor. Like I mentioned, it's against the official style-guide, but you should be able to override colors with the `-s` flag when running `set-option|set` in your local config.

**Comment by rogeruiz** [comment]
Also, if you ever need to unset this option after setting it then you'll need to the use the `-U` flag for `set-option` like so.

```sh
set-option -U pane-active-border-style
```

This will reset the option back to what it originally is set to in the Catppuccin theme(s).

**Comment by opakholis** [comment]
Hi @rogeruiz, sorry for this very very long delay.

I seem to learn a lot of new things here, very insightful. And most importantly, I found the answer I was looking for thanks to you🍻
