### ISSUE TITLE
Discoloring Window Status Background

### ISSUE THREAD

**Issue by AlanD20** [catppuccin/tmux#224]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your problem.

Hi! after updating catppuccin to the latest version, the window status background is discoloring when something new is opening up.

Here is a picture. the first index is the original background color, and the second index is when the discoloring happens and it goes away once I switch to the discolored window then switch back to something else. 

![image](https://github.com/catppuccin/tmux/assets/30084112/72f1141f-1db4-44e6-acd9-7f40728e40e9)

I'm not very familiar with the project but I went through the commits, and apparently #175 caused the issue. A commit before that PR (e2d345648cb7e56302ee82fec6cafbbd8db23129) works  fine but when switching to that PR's merge commit (a1079943b6850b2ebb8214f5067edd4d7f5b4deb), the issue appears again.

I use sway with alacritty with low opacity.

thanks!

### Paste your configuration.

Here is my tmux configuration, where you can find the catppuccin configs at the end of the file:
https://github.com/AlanD20/.dotfiles/blob/main/tmux/.config/tmux/tmux.conf

### What tmux version are you seeing the issue on?

tmux 3.4

**Comment by vdbe** [comment]
The option `@catppuccin_status_right_separator_inverse` was removed in that PR, you seem to have it set but should not have any effect on this.

Wat you are seeing is the `window-status-activity` you can enable disable the color change with `tmux setw window-status-activity-style none`. See #199 for a bit more info.

I think the reason that that PR has this effect is because it started setting and using bg default, which is inverted on activity.

**Comment by AlanD20** [comment]
Yea, looks like setting the style for window status activity to `none` does the job. Thanks!

By the way, I saw in the PR that `@catppuccin_status_right_separator_inverse` option was removed but somehow forgot to also remove it from my config :) thanks for the reminder!
