### ISSUE TITLE
New behaviour prevents styling which was possible in older versions

### ISSUE THREAD

**Issue by alexkornitzer** [catppuccin/tmux#351]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your problem.

It is no longer possible apply a middle separator to fill mode `all`. This appears to be due to consistency in the fg and bg. From looking at the code I think the only way to solve this would be to add an invert variable so that non block characters could be used.  For example inverting fg/bg on line `195` allows `set -g @catppuccin_window_middle_separator " |"` to be used.

Before
<img width="87" alt="Screenshot 2024-10-03 at 14 52 15" src="https://github.com/user-attachments/assets/b3a44f78-aec6-4bd4-98d7-0a6a4d7b0265">

After
<img width="59" alt="Screenshot 2024-10-03 at 14 51 24" src="https://github.com/user-attachments/assets/7ec0c50e-1832-4d74-92e1-74c1f6a1b83b">

### Paste your configuration.

```
set -g @catppuccin_flavour 'mocha'

set -g @catppuccin_pane_active_border_style "fg=#{@thm_peach}"
set -g @catppuccin_pane_border_style "fg=#{@thm_surface_0}"
set -g @catppuccin_status_left_separator ""
set -g @catppuccin_status_right_separator "█"
set -g @catppuccin_window_current_fill "all"
set -g @catppuccin_window_default_fill "none"
set -g @catppuccin_window_left_separator "█"
set -g @catppuccin_window_middle_separator " |"
set -g @catppuccin_window_right_separator "█"
set -g @catppuccin_window_status_style "custom"

set -g @catppuccin_status_background "#181825"
```

### What tmux version are you seeing the issue on?

tmux 3.6

**Comment by rbhanot4739** [comment]
+1 On this. Also `set -g @catppuccin_status_justify "centre"` does not seem to work. Using tmux version 3.4.

**Comment by kjnsn** [comment]
This is on purpose. I'm a bit hesitant to complicate the plugin with more branches of logic, when the same thing can be achieved with three lines of tmux config:

`set -g @catppuccin_window_status_style "none"`
`set -gF window-status-current-format "#[fg=#{@thm_crust},bg=#{@thm_peach}]" ##I | ##T `
`set -gF window-status-format "#[fg=#{@thm_fg},bg=#{@thm_surface_0}]" ##I | ##T `

Overall the approach is to work _with_ tmux, rather than placing another layer of configuration on top of what tmux already provides. This obviously has pros and cons, however it often is much simpler to use the tmux options

**Comment by rbhanot4739** [comment]
How do we keep the windows in the relative center like it used to be with `justify centre` in the previous version. 

Does all the options still continue to work ?

**Comment by kjnsn** [comment]
That's a tmux option, not a catppuccin option. See `status-justify` in https://man7.org/linux/man-pages/man1/tmux.1.html

**Comment by alexkornitzer** [comment]
Understood, thank you for providing the example.
