### ISSUE TITLE
Configuration examples don't look correct.

### ISSUE THREAD

**Issue by bushblade** [catppuccin/tmux#62]
Just trying out config after #57  and I notice the example configs in the README don't look the same for me.
I am using Alacritty and Victor Mono Nerd Font.

Here is what I see for config 2:

![config2](https://github.com/catppuccin/tmux/assets/21976188/763a0638-a5f2-4fc3-9476-8d2ec08e34b0)

And this is config 3:

![config3](https://github.com/catppuccin/tmux/assets/21976188/3f6bc7c1-fae4-4d58-90a8-a53b83202ae6)

config 1 looks the same as the screenshot in the README.

**Comment by 89iuv** [comment]
Looking into it.

**Comment by 89iuv** [comment]
The problem was with a variable that was being re-used. This created a very strange behaviour where changing a setting was not registered on reload.

I have updated the readme fixing the configs and the typo with double "c".
Also added a note to do a: tmux kill-server after changing to a new config preset. This is needed because tmux remembers the global variables between reloads unless you explicitly override them.

Please let me know if the issue still persists.

**Comment by bushblade** [comment]
Thanks @89iuv this does indeed fix the issues for me.
There are still some differences in the separators for me, but  I believe that is related to my font.
For example in config 3 I need to replace
```
set -g @catppuccin_window_middle_separator " █"
```
With
```
set -g @catppuccin_window_middle_separator "█"
```
