### ISSUE TITLE
Window number slightly off

### ISSUE THREAD

**Issue by carter-twi** [catppuccin/tmux#69]
Hi there! 
This may be an issue with my font (using FiraCode Nerd Font), but I've noticed that the window number is slightly off and shows almost like a box around it (see below). Any idea why that may be like that? Thanks!
![image](https://github.com/catppuccin/tmux/assets/131391884/dd9ecd97-c3b8-456e-a69e-61120d55cc4c)

Relevant tmux.conf part:
```# config 2 catppuccin theme
set -g @catppuccin_window_left_separator "█"
set -g @catppuccin_window_right_separator "█ "
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_middle_separator "  █"

set -g @catppuccin_window_default_fill "number"

set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_text "#W"

set -g @catppuccin_status_left_separator  ""
set -g @catppuccin_status_right_separator " "
set -g @catppuccin_status_right_separator_inverse "yes"
set -g @catppuccin_status_fill "all"
set -g @catppuccin_status_connect_separator "no"```

**Comment by 89iuv** [comment]
hi @carter-twi this problem is with how the terminal renders fonts. Here is a better explanation: https://github.com/romkatv/powerlevel10k#sub-pixel-imperfections-around-powerline-symbols

In this case the space between the number and the left or right separator is a unicode character making the number look off.

**Comment by carter-twi** [comment]
Thanks for the link. I greatly appreciate it.
