### ISSUE TITLE
Every window title is displayed as my Mac username

### ISSUE THREAD

**Issue by lightbluepoppy** [catppuccin/tmux#76]
`<Prefix>+w` shows the true window names while catppuccin's theme does not somehow.

**Comment by 89iuv** [comment]
By default the theme will display the current working folder. In your case if you open tmux in your home folder you will see your username because that is the current working folder name.

If you want you can override the behaviour you can use:
set -g @catppuccin_window_default_text "#W"

This will display the application running instead of the current working folder.

**Comment by lightbluepoppy** [comment]
> By default the theme will display the current working folder. In your case if you open tmux in your home folder you will see your username because that is the current working folder name.
> 
> You can override this behaviour with: set -g @catppuccin_window_default_text "#W" set -g @catppuccin_window_current_text "#W"
> 
> This will display the application running instead of the current working folder.

Thank you for the information. I'm afraid I did not read through the document carefully. It would be helpful for new users if the document said that the `@catppuccin_window_default_text` is set to the working directory name.

**Comment by 4rgc** [comment]
This didn't work for me but I found an updated solution for those interested: https://github.com/catppuccin/tmux/issues/227#issuecomment-2452919378

**Comment by whexy** [comment]
It’s now `@catppuccin_window_text` instead of `@catppuccin_window_default_text`.

Hope this saves anyone who trace down to here a few minutes :-)
